#!/bin/sh

SRC=version.ml
PROG=luli
VERSION=`cat ../VERSION`
DATE=`date '+%Y%m%d'`
REVISION=`git show --format='%h' -s`

cat <<EOF > $SRC
(* This file is automatically generated. Do not edit! *)

let version = "$VERSION"
let date = "$DATE"
let revision = "$REVISION"
EOF
